# Generated by Django 5.2.5 on 2025-08-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='users.participant')),
            ],
        ),
    ]
