# Generated by Django 5.2.5 on 2025-08-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('properties', models.JSONField(default=dict)),
                ('participant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_types.participanttype')),
            ],
        ),
    ]
