# Generated by Django 5.2.5 on 2025-08-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='workshops.session')),
            ],
            options={
                'verbose_name': 'Admin Comment',
                'verbose_name_plural': 'Admin Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
