# Generated by Django 5.2.5 on 2025-08-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('attended_count', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('impact_summary', models.TextField(blank=True, null=True)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='workshops.session')),
            ],
        ),
    ]
